package core

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// User represents a system user
type User struct {
	ID                  uuid.UUID `gorm:"type:uuid;primaryKey"`
	Email               string    `gorm:"uniqueIndex;not null"`
	PasswordHash        string    `gorm:"not null"` // Empty for SSO users
	FullName            string
	CompanyID           uuid.UUID `gorm:"index"`
	EmailVerified       bool      `gorm:"default:false"`
	SSOProvider         string    // google, microsoft, saml
	SSOSubject          string
	OnboardingCompleted bool `gorm:"default:false"`

	// KYC / Profile Details
	PhoneNumber    string
	PhoneCode      string
	DateOfBirth    string // YYYY-MM-DD
	AddressStreet  string
	AddressCity    string
	AddressState   string
	AddressZip     string
	AddressCountry string
	IDType         string
	IDNumber       string
	IDExpiry       string // YYYY-MM-DD
	IssuingCountry string

	// Compliance
	ApplicantID string
	KYCStatus   string // init, pending, approved, rejected

	// Advanced Auth
	ResetToken              string
	ResetTokenExpiresAt     time.Time
	MagicLinkToken          string
	MagicLinkTokenExpiresAt time.Time
	TwoFactorEnabled        bool
	TwoFactorSecret         string

	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`

	// Relationships
	Company   Company
	UserRoles []UserRole
}

// Company represents a tenant
type Company struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	Name      string    `gorm:"not null"`
	Domain    string    `gorm:"uniqueIndex"`
	Website   string
	Size      string
	Industry  string
	Location  string // Country
	CreatedAt time.Time
	UpdatedAt time.Time
}

// APIKey represents a developer API key generated by a company
type APIKey struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID uuid.UUID `gorm:"index;not null"`
	CreatedBy uuid.UUID `gorm:"not null"` // User who created the key
	Name      string    `gorm:"not null"`
	Prefix    string    `gorm:"not null"`             // The visible part of the key (e.g., velo_live_1234...)
	Hash      string    `gorm:"uniqueIndex;not null"` // Bcrypt hash of the actual secret key
	Revoked   bool      `gorm:"default:false"`
	LastUsed  *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

// WebhookEndpoint represents a URL to receive events
type WebhookEndpoint struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID   uuid.UUID `gorm:"index;not null"`
	URL         string    `gorm:"not null"`
	Secret      string    `gorm:"not null"`   // Used to sign payloads
	Events      JSON      `gorm:"type:jsonb"` // Array of event types (e.g., ["batch.executed", "deposit.received"])
	IsActive    bool      `gorm:"default:true"`
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// WebhookDelivery records attempt to send a webhook
type WebhookDelivery struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	EndpointID   uuid.UUID `gorm:"index;not null"`
	EventID      string    `gorm:"index;not null"`
	EventType    string    `gorm:"not null"`
	Payload      JSON      `gorm:"type:jsonb"`
	StatusCode   int
	ResponseBody string
	Success      bool
	Attempt      int
	CreatedAt    time.Time
}

// AuditLog represents an immutable record of a system action
type AuditLog struct {
	ID         uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID  uuid.UUID `gorm:"index;not null"`
	UserID     uuid.UUID `gorm:"index"` // Null pointer/zero for system actions
	Action     string    `gorm:"index;not null"`
	Resource   string    `gorm:"index;not null"`
	ResourceID string    `gorm:"index"`
	Details    JSON      `gorm:"type:jsonb"`
	IPAddress  string
	UserAgent  string
	CreatedAt  time.Time
}

// CorporateCard represents a physical or virtual card issued to an employee
type CorporateCard struct {
	ID             uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID      uuid.UUID `gorm:"index;not null"`
	UserID         uuid.UUID `gorm:"index;not null"`   // Assigned employee
	Type           string    `gorm:"not null"`         // "physical" or "virtual"
	Status         string    `gorm:"default:'active'"` // active, frozen, canceled
	Last4          string    `gorm:"not null"`
	ExpiryMonth    int       `gorm:"not null"`
	ExpiryYear     int       `gorm:"not null"`
	DailyLimit     int       `gorm:"default:0"` // 0 = no specific limit
	MonthlyLimit   int       `gorm:"default:0"` // 0 = no specific limit
	ProviderCardID string    // ID from Stripe/Marqeta
	CVV            string    // 3 or 4 digit security code
	ShippingStatus string    // e.g., 'shipped', 'delivered' (physical only)
	TrackingNumber string    // Mock carrier tracking number
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// YieldBalance represents the funds a company has allocated to earn interest
type YieldBalance struct {
	CompanyID         uuid.UUID `gorm:"primaryKey;type:uuid"`
	AllocatedAmount   int       // Amount currently in yield protocol (cents)
	EarnedInterest    int       // Total interest earned so far (cents)
	CurrentAPY        float64   // e.g., 4.25
	LastAccrualTime   time.Time
	ProviderReference string // Mock protocol ref (e.g. Aave/Compound)
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Integration represents a connection to a third-party service (e.g., QuickBooks, Xero)
type Integration struct {
	ID           uuid.UUID `gorm:"primaryKey;type:uuid"`
	CompanyID    uuid.UUID `gorm:"index;not null"`
	Provider     string    // "quickbooks", "xero", "netsuite"
	Status       string    // "connected", "disconnected", "error"
	AccessToken  string    // Encrypted in a real app
	RefreshToken string    // Encrypted
	ExpiresAt    time.Time
	SyncSettings string // JSON string for specific sync options
	LastSyncAt   time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// TaxDocument represents a W-9, W-8BEN, or generated 1099
type TaxDocument struct {
	ID        uuid.UUID `gorm:"primaryKey;type:uuid"`
	CompanyID uuid.UUID `gorm:"index;not null"`
	UserID    uuid.UUID `gorm:"index;not null"`
	Type      string    // w9, w8ben, 1099
	Year      int       // Tax year, e.g., 2026
	Status    string    // pending, verified, rejected, generated
	FileURL   string    // S3 or mock file URL
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Invoice represents a B2B invoice generated for a client.
type Invoice struct {
	ID          uuid.UUID `gorm:"primaryKey;type:uuid"`
	CompanyID   uuid.UUID `gorm:"index;not null"`
	ClientName  string    `gorm:"not null"`
	ClientEmail string    `gorm:"not null"`
	Amount      int       // In cents
	Currency    string    // e.g., "USDC", "USD"
	Status      string    // "pending", "paid", "overdue", "cancelled"
	DueDate     time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// SubAccount represents a departmental checking/budgeting account
type SubAccount struct {
	ID         uuid.UUID  `gorm:"primaryKey;type:uuid"`
	CompanyID  uuid.UUID  `gorm:"index;not null"`
	WalletID   uuid.UUID  `gorm:"index;not null"` // Master treasury wallet
	Name       string     // "Marketing", "Engineering"
	Balance    int        // Allocated funds in cents
	Currency   string     // e.g., "USDC"
	ManagerID  *uuid.UUID `gorm:"index"` // Optional manager assigned for RBAC
	SpendLimit int        // Monthly spend limit in cents
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Role represents a user role (RBAC)
type Role struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	Name         string    `gorm:"uniqueIndex;not null"` // owner, finance_manager, etc.
	Description  string
	IsSystemRole bool `gorm:"default:false"`
}

// Permission represents a specific action on a resource
type Permission struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	Resource    string    `gorm:"not null"` // payroll, wallet, etc.
	Action      string    `gorm:"not null"` // create, read, execution, etc.
	Description string
}

// RolePermission maps roles to permissions
type RolePermission struct {
	RoleID       uuid.UUID `gorm:"primaryKey"`
	PermissionID uuid.UUID `gorm:"primaryKey"`
	Conditions   JSON      `gorm:"type:jsonb"` // e.g. {"max_amount": 100000}
}

// UserRole maps users to roles within a company
type UserRole struct {
	ID         uuid.UUID `gorm:"type:uuid;primaryKey"`
	UserID     uuid.UUID `gorm:"uniqueIndex:idx_user_company_role"`
	CompanyID  uuid.UUID `gorm:"uniqueIndex:idx_user_company_role"`
	RoleID     uuid.UUID
	AssignedBy uuid.UUID
	CreatedAt  time.Time

	Role Role
}

type JSON map[string]interface{}

func (j JSON) Value() (driver.Value, error) {
	if j == nil {
		return nil, nil
	}
	bytes, err := json.Marshal(j)
	return string(bytes), err
}

func (j *JSON) Scan(value interface{}) error {
	if value == nil {
		*j = make(JSON)
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		str, okStr := value.(string)
		if !okStr {
			return errors.New("type assertion to []byte or string failed")
		}
		bytes = []byte(str)
	}

	return json.Unmarshal(bytes, &j)
}
