package core

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// User represents a system user
type User struct {
	ID                  uuid.UUID `gorm:"type:uuid;primaryKey"`
	Email               string    `gorm:"uniqueIndex;not null"`
	PasswordHash        string    `gorm:"not null"` // Empty for SSO users
	FullName            string
	CompanyID           uuid.UUID `gorm:"index"`
	EmailVerified       bool      `gorm:"default:false"`
	SSOProvider         string    // google, microsoft, saml
	SSOSubject          string
	OnboardingCompleted bool `gorm:"default:false"`

	// KYC / Profile Details
	PhoneNumber    string
	PhoneCode      string
	DateOfBirth    string // YYYY-MM-DD
	AddressStreet  string
	AddressCity    string
	AddressState   string
	AddressZip     string
	AddressCountry string
	IDType         string
	IDNumber       string
	IDExpiry       string // YYYY-MM-DD
	IssuingCountry string

	// Compliance
	ApplicantID string
	KYCStatus   string // init, pending, approved, rejected

	// Advanced Auth
	ResetToken              string
	ResetTokenExpiresAt     time.Time
	MagicLinkToken          string
	MagicLinkTokenExpiresAt time.Time
	TwoFactorEnabled        bool
	TwoFactorSecret         string

	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`

	// Relationships
	Company   Company
	UserRoles []UserRole
}

// Company represents a tenant
type Company struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	Name      string    `gorm:"not null"`
	Domain    string    `gorm:"uniqueIndex"`
	Website   string
	Size      string
	Industry  string
	Location  string // Country
	CreatedAt time.Time
	UpdatedAt time.Time
}

// APIKey represents a developer API key generated by a company
type APIKey struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID uuid.UUID `gorm:"index;not null"`
	CreatedBy uuid.UUID `gorm:"not null"` // User who created the key
	Name      string    `gorm:"not null"`
	Prefix    string    `gorm:"not null"`             // The visible part of the key (e.g., velo_live_1234...)
	Hash      string    `gorm:"uniqueIndex;not null"` // Bcrypt hash of the actual secret key
	Revoked   bool      `gorm:"default:false"`
	LastUsed  *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

// WebhookEndpoint represents a URL to receive events
type WebhookEndpoint struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID   uuid.UUID `gorm:"index;not null"`
	URL         string    `gorm:"not null"`
	Secret      string    `gorm:"not null"`   // Used to sign payloads
	Events      JSON      `gorm:"type:jsonb"` // Array of event types (e.g., ["batch.executed", "deposit.received"])
	IsActive    bool      `gorm:"default:true"`
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// WebhookDelivery records attempt to send a webhook
type WebhookDelivery struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	EndpointID   uuid.UUID `gorm:"index;not null"`
	EventID      string    `gorm:"index;not null"`
	EventType    string    `gorm:"not null"`
	Payload      JSON      `gorm:"type:jsonb"`
	StatusCode   int
	ResponseBody string
	Success      bool
	Attempt      int
	CreatedAt    time.Time
}

// AuditLog represents an immutable record of a system action
type AuditLog struct {
	ID         uuid.UUID `gorm:"type:uuid;primaryKey"`
	CompanyID  uuid.UUID `gorm:"index;not null"`
	UserID     uuid.UUID `gorm:"index"` // Null pointer/zero for system actions
	Action     string    `gorm:"index;not null"`
	Resource   string    `gorm:"index;not null"`
	ResourceID string    `gorm:"index"`
	Details    JSON      `gorm:"type:jsonb"`
	IPAddress  string
	UserAgent  string
	CreatedAt  time.Time
}

// Role represents a user role (RBAC)
type Role struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	Name         string    `gorm:"uniqueIndex;not null"` // owner, finance_manager, etc.
	Description  string
	IsSystemRole bool `gorm:"default:false"`
}

// Permission represents a specific action on a resource
type Permission struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	Resource    string    `gorm:"not null"` // payroll, wallet, etc.
	Action      string    `gorm:"not null"` // create, read, execution, etc.
	Description string
}

// RolePermission maps roles to permissions
type RolePermission struct {
	RoleID       uuid.UUID `gorm:"primaryKey"`
	PermissionID uuid.UUID `gorm:"primaryKey"`
	Conditions   JSON      `gorm:"type:jsonb"` // e.g. {"max_amount": 100000}
}

// UserRole maps users to roles within a company
type UserRole struct {
	ID         uuid.UUID `gorm:"type:uuid;primaryKey"`
	UserID     uuid.UUID `gorm:"uniqueIndex:idx_user_company_role"`
	CompanyID  uuid.UUID `gorm:"uniqueIndex:idx_user_company_role"`
	RoleID     uuid.UUID
	AssignedBy uuid.UUID
	CreatedAt  time.Time

	Role Role
}

type JSON map[string]interface{}

func (j JSON) Value() (interface{}, error) {
	return j, nil
}

func (j *JSON) Scan(value interface{}) error {
	return nil // Simplified for MVP
}
